name: Continuous Integration
on: pull_request
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Install vue
        run: yarn global add @vue/cli
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn electron:build